# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17c0289e9ba158f9867ae4dd92f31de2e3d24059256a789acf9ce3f940a777fc7eb48ca2ed2f39f6c301589f12e5d997755a392e8d7ea247fe9404f3a47a8f54

test:
  secret_key_base: a06a3a8d4843c211af9785f1315ebe11eb2a82617b884c36b6ab2e68cb680e02c2176880cfcf95d7638414e3af2e44ada142e0b198cf4b5fe81b710e73a86cab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
